"""Add constrains column to exam

Revision ID: 26200d49af90
Revises: 33358c0f4303
Create Date: 2026-01-31 22:47:10.816937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26200d49af90'
down_revision: Union[str, Sequence[str], None] = '33358c0f4303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'constraints')
    # ### end Alembic commands ###
