"""Alter Teacher table

Revision ID: 2fd2a11b7bf6
Revises: 4dbe86561ba2
Create Date: 2026-02-26 15:05:52.252926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd2a11b7bf6'
down_revision: Union[str, Sequence[str], None] = '4dbe86561ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('username', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=False)
    op.create_index(op.f('ix_teachers_username'), 'teachers', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_username'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_column('teachers', 'last_name')
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'password_hash')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'username')
    # ### end Alembic commands ###
