"""Add status column to exam

Revision ID: 33358c0f4303
Revises: d2903f7e58b5
Create Date: 2026-01-31 20:56:47.583398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33358c0f4303'
down_revision: Union[str, Sequence[str], None] = 'd2903f7e58b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('status', sa.Enum('draft', 'final', name='examstatus'), nullable=False,server_default='draft'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'status')
    # ### end Alembic commands ###
