"""Add Teacher Table

Revision ID: 4dbe86561ba2
Revises: cfaa9cb5046b
Create Date: 2026-02-26 00:26:55.295612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbe86561ba2'
down_revision: Union[str, Sequence[str], None] = 'cfaa9cb5046b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'teacher_id')
    # ### end Alembic commands ###
