"""Add file_path for chapter

Revision ID: f78b4265843e
Revises: 2fd2a11b7bf6
Create Date: 2026-03-07 16:41:16.964412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78b4265843e'
down_revision: Union[str, Sequence[str], None] = '2fd2a11b7bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'file_path')
    # ### end Alembic commands ###
